batch_size: 8
learning_rate: 0.0003
input_channels: 3
input_width: 500
input_height: 500
output_size: 90000
epochs: 15

train_dir: dataset/corner-scan-v2/train-raw
gt_dir: dataset/corner-scan-v2/ground-truth
validation_fraction: 0.2

plots_dir: plots/first-plots

