batch_size: 6
learning_rate: 0.0003
input_channels: 3
input_width: 500
input_height: 500
output_size: 90000
epochs: 10

train_dir: dataset/corner-scan-v2/train-raw
gt_dir: dataset/corner-scan-v2/ground-truth
validation_fraction: 0.1
test_dir: dataset/real-scans-v1-resized

plots_dir: plots
model: wide
model_save_dir: models/saved

