batch_size: 8
learning_rate: 0.0003
input_channels: 3
input_width: 300
input_height: 300
output_size: 90000
epochs: 30

train_dir: dataset/train-filt
gt_dir: dataset/ground-truth
validation_fraction: 0.2

